services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dairinin
      POSTGRES_PASSWORD: dairinin
      POSTGRES_DB: dairinin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
